env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - prettier
  - plugin:import/recommended
  - plugin:n/recommended
  - plugin:security/recommended

plugins:
  - import
  - n
  - security

root: true

rules:
  n/no-deprecated-api: off
  n/no-unsupported-features/es-syntax: off
  n/no-unsupported-features/node-builtins: off
  n/no-unpublished-require: off
  n/no-unpublished-import: off
  n/no-process-exit: off
  # This forces using file extensions in imports, which is a best practice, but refactoring would take some time
  n/no-missing-import: off

  security/detect-non-literal-fs-filename: off
  security/detect-object-injection: off

  no-unused-vars: [error, {argsIgnorePattern: "^_|err|event|next|reject"}]
  require-atomic-updates: warn

settings:
  import/ignore:
    - app/locale.js
